export function getVideoThumb(url = "") {
  if (!url) return null;
  const yt = url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([\w-]{6,})/);
  if (yt) return { thumb: `https://img.youtube.com/vi/${yt[1]}/hqdefault.jpg`, watchUrl: `https://www.youtube.com/watch?v=${yt[1]}`, videoId: yt[1] };
  return null;
}
// Short (mostly under a minute), verified proper-form demonstrations for the exercises actually in use across client programs.
export const DEFAULT_EXERCISE_VIDEOS = {
  "Back Squat": "https://www.youtube.com/watch?v=5MXoGtPBz-I",
  "Barbell Bench Press": "https://www.youtube.com/shorts/hWbUlkb5Ms4",
  "Barbell Curl": "https://www.youtube.com/shorts/dIAxyJimXnA",
  "Barbell Row": "https://www.youtube.com/shorts/Nqh7q3zDCoQ",
  "Deadlift": "https://www.youtube.com/shorts/8np3vKDBJfc",
  "Dumbbell Row": "https://www.youtube.com/shorts/H8jf3DwlIlo",
  "Goblet Squat": "https://www.youtube.com/shorts/wjkoL-CagYE",
  "Incline DB Press": "https://www.youtube.com/shorts/8fXfwG4ftaQ",
  "Kettlebell Swing": "https://www.youtube.com/shorts/aSYap2yhW8s",
  "Leg Press": "https://www.youtube.com/shorts/nDh_BlnLCGc",
  "Overhead Press": "https://www.youtube.com/shorts/zoN5EH50Dro",
  "Plank": "https://www.youtube.com/shorts/hoeNgjheDHk",
  "Pull-Up": "https://www.youtube.com/shorts/ZPG8OsHKXLw",
  "Push-Up": "https://www.youtube.com/shorts/zUymek3A64A",
  "Romanian Deadlift": "https://www.youtube.com/shorts/8tm3JW1UpAs",
  "Triceps Pushdown": "https://www.youtube.com/shorts/leazgWMaSo8",
  "Lat Pulldown": "https://www.youtube.com/shorts/bNmvKpJSWKM",
  "Seated Leg Curl": "https://www.youtube.com/shorts/EnZZIaPCb8k",
  "Leg Extension": "https://www.youtube.com/shorts/iQ92TuvBqRo",
  "DB Lateral Raises": "https://www.youtube.com/shorts/Kl3LEzQ5Zqs",
  "Barbell Hip Thrust": "https://www.youtube.com/shorts/CcwyvfJcoeA",
  "Face Pull": "https://www.youtube.com/shorts/7kXfVIwmfwE",
  "Dumbbell Lunge": "https://www.youtube.com/watch?v=K5NhC44yuR8",
  "V-Squat": "https://www.youtube.com/shorts/OqSs_szse5U",
  "Split Squat": "https://www.youtube.com/shorts/iUOoNilQWEs",
  "Box Squat": "https://www.youtube.com/shorts/bcATXo7c6yU",
  "Dead Hang": "https://www.youtube.com/shorts/dOCQjaasbGs",
  "Chest-Supported Row": "https://www.youtube.com/shorts/09wri23R4SU",
  "Pec Deck Fly": "https://www.youtube.com/shorts/CRroep849bU",
  "Step-Up": "https://www.youtube.com/shorts/-D8rH8OGt4E",
  "Step Down": "https://www.youtube.com/shorts/qE-Azuf7XPE",
  "SkiErg": "https://www.youtube.com/shorts/3Qfhi3WXjbA",
  "Sled Push": "https://www.youtube.com/shorts/KkGWazCx93A",
  "Sled Pull": "https://www.youtube.com/shorts/o2JhIsqispo",
  "Assisted Pull-Up": "https://www.youtube.com/shorts/Nqy1rtyVH2o",
  "Lying Leg Curl": "https://www.youtube.com/shorts/bgfHeL6eR9Q",
  "Hip Abduction Machine": "https://www.youtube.com/shorts/Z6Aq5upUp4A",
  "Standing Calf Raise": "https://www.youtube.com/shorts/B30JglFGx8Y",
  "Machine Ab Crunch": "https://www.youtube.com/shorts/2lSf2F7RUAU",
  "Farmers Carry": "https://www.youtube.com/shorts/8RXTKE06mKc",
  "Farmer's Carry": "https://www.youtube.com/shorts/8RXTKE06mKc",
  "Walking Lunge": "https://www.youtube.com/shorts/5eQd_hsXESI",
  "Incline DB Chest Press": "https://www.youtube.com/shorts/8fXfwG4ftaQ",
  "Flat Barbell Bench Press": "https://www.youtube.com/shorts/hWbUlkb5Ms4",
  "Neutral Grip Lat Pulldown": "https://www.youtube.com/shorts/bNmvKpJSWKM",
  "Incline DB Shoulder Press": "https://www.youtube.com/shorts/k6tzKisR3NY",
  "Incline Shoulder DB Press": "https://www.youtube.com/shorts/k6tzKisR3NY",
  "Hip Thrust": "https://www.youtube.com/shorts/CcwyvfJcoeA",
  "Smith Machine Hip Thrust": "https://www.youtube.com/shorts/CcwyvfJcoeA",
  "Single-Leg Hip Thrust": "https://www.youtube.com/shorts/CcwyvfJcoeA",
  "Machine Hip Thrust": "https://www.youtube.com/shorts/CcwyvfJcoeA",
  "Cable Glute Kickback": "https://www.youtube.com/shorts/n-cgsNePyFo",
  "Machine Glute Kickback": "https://www.youtube.com/shorts/n-cgsNePyFo",
  "Cable Kickback": "https://www.youtube.com/shorts/n-cgsNePyFo",
  "Kickback Machine": "https://www.youtube.com/shorts/n-cgsNePyFo",
  "45-Degree Back Extension": "https://www.youtube.com/shorts/VH4Bqn1FUhM",
  "45 Degree Glute Extension": "https://www.youtube.com/shorts/VH4Bqn1FUhM",
  "Back Extension": "https://www.youtube.com/shorts/VH4Bqn1FUhM",
  "Machine Back Extension": "https://www.youtube.com/shorts/VH4Bqn1FUhM",
};
