// Supabase Edge Function: forge-ai-report
// Drafts the qualitative parts of a client's nutrition report (verdict,
// working/issues, food swaps, a target day, supplement review, next step,
// and proposed macro targets) from a week's logged data, using Google's
// Gemini API (free tier - see README below). Numeric averages are computed
// client-side from real logged macro data (see src/lib/aiReport.js) and
// merged in afterwards, NOT generated by the model - the model should
// never be trusted to do arithmetic, only to read numbers a human/deter-
// ministic code already computed and write sensible prose/food advice
// around them.
//
// This is a DRAFT only. The coach reviews/edits the returned JSON in the
// existing "Set report" textarea (NutritionFlow.jsx) before it's saved and
// shown to the client - nothing here writes to the database or reaches a
// client directly.
//
// Secret required: GEMINI_API_KEY
//   1. Get a free key: https://aistudio.google.com/apikey (Google account,
//      no payment method needed - the free tier is generous: as of writing,
//      ~15 requests/minute and 1,500 requests/day on gemini-2.0-flash).
//   2. Set it on this project: either
//        supabase secrets set GEMINI_API_KEY=your-key-here
//      or Supabase Dashboard -> Edge Functions -> Manage secrets.
//   3. Deploy this function: supabase functions deploy forge-ai-report
//      (or paste this file's contents into Dashboard -> Edge Functions ->
//      New Function, named exactly "forge-ai-report", if you'd rather not
//      use the CLI).

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const GEMINI_MODEL = "gemini-2.0-flash";

// The model only ever generates these fields - averages are computed
// deterministically and merged in by the caller (aiReport.js), never by
// the model.
const RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    verdict: { type: "STRING", description: "One encouraging-but-honest sentence summarizing the week, in a coach's voice." },
    targets: {
      type: "OBJECT",
      properties: {
        calories: { type: "INTEGER" },
        protein: { type: "INTEGER" },
        carbs: { type: "INTEGER" },
        fats: { type: "INTEGER" },
      },
      required: ["calories", "protein", "carbs", "fats"],
    },
    working: { type: "ARRAY", items: { type: "STRING" }, description: "1-4 short bullet points on what's going well." },
    issues: { type: "ARRAY", items: { type: "STRING" }, description: "1-4 short bullet points on what's going wrong. Empty array if nothing's wrong." },
    swaps: {
      type: "ARRAY",
      description: "0-3 concrete food swaps.",
      items: {
        type: "OBJECT",
        properties: { from: { type: "STRING" }, to: { type: "STRING" }, why: { type: "STRING" } },
        required: ["from", "to"],
      },
    },
    targetDay: {
      type: "OBJECT",
      properties: {
        meals: {
          type: "ARRAY",
          items: {
            type: "OBJECT",
            properties: { slot: { type: "STRING" }, description: { type: "STRING" }, time: { type: "STRING" } },
            required: ["slot", "description"],
          },
        },
      },
      required: ["meals"],
    },
    supplementReview: { type: "STRING", description: "1-2 sentences, or empty string if no supplement stack was provided." },
    nextStep: { type: "STRING", description: "One clear, specific instruction for the client's next phase." },
  },
  required: ["verdict", "targets", "working", "issues", "swaps", "targetDay", "supplementReview", "nextStep"],
};

function buildPrompt(input: any): string {
  const { goal, weightKg, phase, weekSummary, hasNumericData, supplementStack } = input;
  return `You are an experienced physique/performance nutrition coach writing a weekly check-in report for your client. Be direct, specific, and encouraging - never generic filler. Base every claim strictly on the data given below; if data is thin, say so plainly rather than inventing specifics.

CLIENT
- Goal: ${goal || "not specified"}
- Bodyweight: ${weightKg ? `${weightKg}kg` : "not specified"}
- Current nutrition phase: ${phase || "not specified"}
- Supplement stack: ${supplementStack || "none logged"}

THIS WEEK'S LOGGED DATA
${weekSummary || "No food was logged this week."}
${hasNumericData ? "" : "\nNote: this client did not use the macro tracker this week (photo/description diary only, no precise numbers) - do not state precise calorie/macro claims about what they ate; base 'working'/'issues' on the food choices and consistency described, not exact numbers."}

TASK
Write the report as JSON matching the given schema:
- verdict: one honest, specific sentence.
- targets: propose calories/protein/carbs/fats for the NEXT phase, grounded in the client's goal and bodyweight (protein roughly 1.6-2.2g/kg bodyweight is a reasonable default absent other info). These are a coach's proposed starting point, not a diagnosis - the coach will review and can edit them.
- working: what's genuinely working, specifically (not "great job!").
- issues: what's genuinely a problem, specifically. Empty array if nothing stands out.
- swaps: concrete swaps only if something in the log clearly warrants one - otherwise return an empty array, don't invent swaps for their own sake.
- targetDay: a realistic one-day meal-by-meal plan (breakfast/lunch/dinner/snacks or similar) hitting the proposed targets, using foods similar to what this client already eats where the log gives you something to go on.
- supplementReview: comment on their actual stack if one was given, else return an empty string.
- nextStep: one clear, actionable instruction for what happens next.`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  const json = (o: any, st = 200) => new Response(JSON.stringify(o), { status: st, headers: { ...CORS, "Content-Type": "application/json" } });
  try {
    const apiKey = Deno.env.get("GEMINI_API_KEY");
    if (!apiKey) return json({ error: "AI report drafting isn't set up yet - missing GEMINI_API_KEY secret." }, 500);

    const body = await req.json().catch(() => ({}));
    const prompt = buildPrompt(body);

    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            responseMimeType: "application/json",
            responseSchema: RESPONSE_SCHEMA,
            temperature: 0.6,
          },
        }),
      }
    );

    const data = await res.json();
    if (!res.ok) {
      return json({ error: data?.error?.message || `Gemini request failed (${res.status})` }, 502);
    }
    const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) return json({ error: "Gemini returned no content - it may have blocked the response (check candidates[0].finishReason)." }, 502);

    let draft: any;
    try {
      draft = JSON.parse(text);
    } catch {
      return json({ error: "Gemini returned malformed JSON." }, 502);
    }

    return json({ draft });
  } catch (e: any) {
    return json({ error: String(e?.message || e) }, 500);
  }
});
